export const SkillDescriptions = {
  "Thủy Tổ": "Trong giai đoạn Hành động, mỗi người chơi mỗi lượt một lần, bạn có thể giao cho họ tùy ý số lá bài trên tay. Lần đầu tiên trong lượt bạn giao tổng cộng từ 2 lá bài trở lên, bạn có thể xem như sử dụng hoặc đánh ra một lá Bài Cơ Bản. \"Trăm họ cùng một cội, muôn dân chung một nguồn.\"",
  "Bọc Trăm Trứng": "Khi bạn cần sử dụng hoặc đánh ra một lá [Chém], một tướng thuộc hệ 🟢 LẠC có thể thay bạn sử dụng hoặc đánh ra lá bài đó.",
  "Thiết Mã": "Khoảng cách từ bạn đến các tướng khác luôn được tính là -1.",
  "Tre Ngà": "Sau khi bạn sử dụng [Chém] và chỉ định mục tiêu, bạn có thể khiến toàn bộ kỹ năng không phải Tỏa Định Kỹ của mục tiêu mất hiệu lực đến hết lượt này. Sau đó tiến hành phán xét; trừ khi mục tiêu bỏ 1 lá bài cùng chất với kết quả phán xét, nếu không họ không thể sử dụng [Né].",
  "Dời Núi": "Bạn có thể sử dụng hoặc đánh ra một lá [Chém] như [Né], hoặc một lá [Né] như [Chém].",
  "Tiên Duyên": "Bạn có thể sử dụng hoặc trọng chú một lá bài ♣ trên tay như [Xiềng Xích].",
  "Tiên Duyên (Tỏa Định Kỹ)": "Bạn sử dụng các lá Cẩm Nang không bị giới hạn khoảng cách.",
  "Hóa Tiên": "Khi bạn rơi vào trạng thái Hấp hối, bạn có thể bỏ toàn bộ bài trên tay, bài Trang bị và bài Phán xét; sau đó đưa tướng về trạng thái ban đầu, rút 3 lá bài và hồi phục Sinh lực đến 3.",
  "Duyên Tiên": "Mỗi khi bạn sử dụng một lá Cẩm Nang Thường, bạn có thể rút 1 lá bài.",
  "Nỏ Thần": "Phạm vi công kích của [Chém] bạn sử dụng bằng đúng điểm số của lá bài đó. Sau khi [Chém] chỉ định mục tiêu, thực hiện các hiệu ứng sau nếu thỏa điều kiện: Nếu số bài trên tay của bạn không ít hơn mục tiêu, họ không thể sử dụng [Né]. Nếu Sinh lực của bạn không nhiều hơn mục tiêu, [Chém] đó gây thêm 1 điểm sát thương.",
  "Bánh Chưng": "Trong giai đoạn Chuẩn bị, bạn có thể xem X lá bài trên cùng của chồng bài rút (X bằng số người chơi còn sống, tối đa 5), sau đó đặt chúng theo thứ tự tùy ý lên đầu hoặc xuống cuối chồng bài rút.",
  "Đạm Bạc": "Nếu bạn không có bài trên tay, bạn không thể trở thành mục tiêu của [Chém] hoặc [Quyết Đấu].",
  "Khai Thiên": "Bạn có thể sử dụng hoặc đánh ra một lá bài Đỏ như một lá [Chém].",
  "Thần Giáp": "Nếu khu Trang bị của bạn không có Giáp, bạn được xem như đã trang bị [Bát Quái Trận].",
  "Thần Hỏa": "Bạn có thể sử dụng một lá bài Đỏ trên tay như [Hỏa Công].",
  "Linh Giám": "Bạn có thể sử dụng một lá bài Đen trên tay như [Hóa Giải].",
  "Dạ Trạch": "Trong giai đoạn Rút bài, bạn có thể thay vào đó thu lấy ngẫu nhiên 1 lá bài trên tay của tối đa 2 tướng khác.",
  "Khởi Nghĩa": "Trong giai đoạn Rút bài, bạn có thể rút ít hơn 1 lá bài. Nếu làm vậy, trong lượt này, [Chém] và [Quyết Đấu] do bạn sử dụng gây thêm 1 điểm sát thương.",
  "Tự Chủ": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể đấu điểm với một tướng có Sinh lực cao hơn bạn. Nếu bạn thắng, chọn một tướng trong phạm vi công kích của họ; họ gây 1 điểm sát thương lên tướng đó. Nếu bạn không thắng, họ gây 1 điểm sát thương lên bạn.",
  "Khoan Dân": "Sau khi bạn nhận sát thương, bạn có thể chọn một tướng. Người đó rút bài cho đến khi số bài trên tay bằng X (X bằng giới hạn Sinh lực của họ, tối đa 5).",
  "Dưỡng Quân": "Bạn có thể thực hiện một hoặc nhiều lựa chọn sau: Bỏ qua giai đoạn Phán xét và giai đoạn Rút bài. Bỏ qua giai đoạn Hành động và bỏ 1 lá bài Trang bị. Bỏ qua giai đoạn Bỏ bài và lật mặt tướng. Mỗi lựa chọn được thực hiện, xem như bạn sử dụng một lá [Chém] không hạn chế cự ly.",
  "Nam Quốc Sơn Hà": "Sau khi bạn nhận sát thương, bạn có thể rút 1 lá bài, rồi thu lấy lá bài gây ra sát thương đó.",
  "Tiên Phát": "Khi bạn cần sử dụng hoặc đánh ra một lá [Né], một tướng thuộc hệ 🔴 VIỆT có thể thay bạn sử dụng hoặc đánh ra lá bài đó.",
  "Đoạt Sáo": "Trong giai đoạn Kết thúc, bạn có thể lật mặt tướng và rút 4 lá bài. Sau đó, bỏ 1 lá bài trên tay; nếu lá bài bị bỏ là Trang bị, bạn được thay vào đó sử dụng lá bài ấy.",
  "Chương Dương": "Bạn có thể sử dụng lá bài trong khu Trang bị như [Hóa Giải]. Khi bạn lật mặt tướng từ mặt sau lên mặt trước, bạn có thể bỏ 1 lá bài, sau đó di chuyển 1 lá bài trên bàn chơi.",
  "Tiên Phong": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể chọn một: Mất 1 điểm Sinh lực; hoặc Bỏ 1 lá bài Vũ khí. Nếu làm vậy, gây 1 điểm sát thương lên một tướng khác trong phạm vi công kích của bạn.",
  "Bạch Đằng": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể bỏ tùy ý số lá bài, sau đó rút số lá bài tương ứng. Nếu bằng cách này bạn bỏ toàn bộ bài trên tay, hãy rút thêm 1 lá bài.",
  "Hậu Viện": "Khi một tướng thuộc hệ 🔵 HÀ sử dụng [Đào] lên bản thân, nếu sinh lực của họ lớn hơn bạn, họ có thể để bạn hồi phục 1 điểm sinh lực thay cho mình. Nếu làm vậy, họ rút 1 lá bài.",
  "Kỳ Tập": "Bạn có thể sử dụng một lá bài Đen như một lá [Tước Bài].",
  "Lặn Sâu": "Trong giai đoạn Hành động, bạn có thể mất 1 điểm Sinh lực, sau đó rút 2 lá bài.",
  "Bình Ngô": "Trong giai đoạn Rút bài, bạn có thể rút thêm 1 lá bài.",
  "Tâm Công": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể chỉ định một tướng khác chọn một chất bài. Sau đó, họ thu lấy ngẫu nhiên 1 lá bài trên tay bạn và mở ra. Nếu chất của lá bài đó khác với chất họ đã chọn, bạn gây 1 điểm sát thương lên họ.",
  "Nghệ An Kế": "Bạn không thể trở thành mục tiêu của [Cướp Bài] và [Hỗn Loạn].",
  "Nhiếp Chính": "Nếu trong giai đoạn Hành động bạn không sử dụng hoặc đánh ra [Chém], thì bạn có thể bỏ qua giai đoạn Bỏ bài.",
  "Thính Chính": "Bạn có thể sử dụng hoặc đánh ra một lá bài Đen trên tay như [Né].",
  "Phật Tâm": "Trong giai đoạn Chuẩn bị, bạn có thể tiến hành phán xét. Nếu kết quả là bài Đen, bạn có thể lặp lại quá trình này. Sau đó, thu lấy tất cả các lá bài phán xét màu Đen.",
  "Thông Ngôn": "Sau khi lá bài phán xét của bạn có hiệu lực, bạn có thể thu lấy lá bài đó.",
  "Hòa Nghị": "Sau khi bạn nhận 1 điểm sát thương, bạn có thể xem 2 lá bài trên cùng của chồng bài rút, sau đó phân phối những lá bài đó cho các tướng tùy ý.",
  "Vân Đồn": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể đấu điểm với một tướng khác. Nếu thắng, trong lượt này bạn được sử dụng thêm 1 lá [Chém], [Chém] không giới hạn cự ly và có thể chỉ định thêm 1 mục tiêu. Nếu không thắng, bạn không thể sử dụng [Chém] trong lượt này.",
  "Đối Sứ": "Sau khi bạn nhận sát thương, bạn có thể thu lấy 1 lá bài từ nguồn sát thương.",
  "Ứng Biến": "Trước khi lá bài phán xét của một người chơi có hiệu lực, bạn có thể đánh ra 1 lá bài trên tay để thay thế lá bài phán xét đó.",
  "Thất Trảm Sớ": "Sau khi bạn nhận sát thương, bạn có thể tiến hành phán xét. Nếu kết quả không phải chất ♥, nguồn sát thương phải chọn một: Bỏ 2 lá bài trên tay; hoặc Nhận 1 điểm sát thương do bạn gây ra.",
  "Duyên Thơ": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể bỏ 2 lá bài trên tay. Sau đó, bạn và một tướng Nam đã bị thương mỗi người hồi phục 1 điểm Sinh lực.",
  "Xuân Hương": "Sau khi bạn mất 1 lá bài ở khu Trang bị, bạn có thể rút 2 lá bài.",
  "Hộ Chủ": "Khi bạn rơi vào trạng thái Hấp hối, lật lá bài trên cùng của chồng bài rút và đặt lên tướng của bạn, gọi là \"Trung\". Nếu điểm số của lá bài này khác với tất cả các lá \"Trung\" đã có, bạn hồi phục đến 1 điểm Sinh lực. Nếu trùng điểm số, bỏ lá bài đó vào chồng bài bỏ. Khi trên tướng của bạn có \"Trung\", giới hạn trữ bài bằng số lá \"Trung\".",
  "Can Gián": "Khi một tướng bị bỏ hoặc bị thu lấy bài trên tay, bạn có thể mất 1 điểm Sinh lực. Nếu làm vậy, tướng đó rút 2 lá bài.",
  "Hiền Hậu": "Khi bạn nhận sát thương, bạn có thể bỏ 1 lá bài ♥ trên tay để ngăn chặn sát thương đó, rồi chọn 1 tướng khác và chọn một: Tướng đó nhận 1 điểm sát thương, sau đó rút X lá bài (X là số Sinh lực đã mất của họ, tối đa 5). Tướng đó mất 1 điểm Sinh lực, sau đó thu lấy lá bài bạn vừa bỏ.",
  "Quốc Sắc": "Mọi lá bài ♠ của bạn được xem như ♥.",
  "Hòa Thân": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể bỏ 1 lá bài và chọn 2 tướng Nam khác. Sau đó, một trong hai tướng được xem như sử dụng một lá [Quyết Đấu] lên người còn lại.",
  "An Bang": "Trong giai đoạn Kết thúc, bạn có thể rút 1 lá bài.",
  "Nam Dược": "Ngoài lượt của bạn, bạn có thể sử dụng một lá bài Đỏ như [Đào].",
  "Diệu Dược": "Trong giai đoạn Hành động, mỗi lượt một lần, bạn có thể bỏ 1 lá bài trên tay để một tướng hồi phục 1 điểm Sinh lực.",
  "Uy Chấn": "Khi một người chơi khác sử dụng [Chém] màu Đỏ gây sát thương cho bạn, người đó phải chọn một: Hồi phục 1 điểm Sinh lực; hoặc Rút 1 lá bài.",
  "Bình Loạn": "Bạn có thể sử dụng 2 lá bài cùng Chất trên tay như một lá [Loạn Tiễn].",
  "Khai Quốc": "Giới hạn số lá bài trên tay của bạn +X (X bằng 2 lần số tướng thuộc hệ 🟤 SƠN).",
  "Phạt Tội": "Khi bạn sử dụng hoặc đánh ra [Né], bạn có thể chọn một người chơi khác tiến hành phán xét. Nếu kết quả là: ♠: Bạn gây 2 điểm sát thương Lôi lên họ. ♣: Bạn hồi phục 1 điểm Sinh lực, sau đó gây 1 điểm sát thương Lôi lên họ.",
  "Quân Cơ": "Trước khi lá bài phán xét của một người chơi có hiệu lực, bạn có thể đánh ra một lá bài Đen để thay thế lá bài phán xét đó.",
  "Định Quốc": "Trong giai đoạn Hành động, mỗi tướng thuộc hệ 🟤 SƠN có thể một lần giao cho bạn một lá [Né] hoặc [Sấm Sét].",
  "Phá Quân": "Sau mỗi khi bạn sử dụng [Chém] chỉ định mục tiêu, họ phải sử dụng 2 lá [Né] mới có thể triệt tiêu. Sau mỗi khi bạn sử dụng [Quyết Đấu] chỉ định mục tiêu, hoặc trở thành mục tiêu của [Quyết Đấu], đối phương phải đánh ra 2 lá [Chém] cho mỗi lần hưởng ứng.",
  "Phá Thành": "Trong giai đoạn Rút bài, bạn có thể thay vào đó tiến hành phán xét. Thu lấy lá bài phán xét đã có hiệu lực. Trong lượt này, bạn có thể sử dụng một lá bài trên tay khác màu với kết quả phán xét như [Quyết Đấu].",
  "Trung Dũng": "Lượt của mỗi người chơi, mỗi lượt một lần, bạn có thể úp 1 lá bài trên tay và sử dụng hoặc đánh ra như bất kỳ lá bài nào. Người chơi khác có thể nghi ngờ và công khai lá bài đó: Nếu là giả, lá bài này vô hiệu. Nếu là thật, người nghi ngờ nhận kỹ năng \"Hộ Giá\".",
  "Hộ Giá": "Bạn không thể nghi ngờ kỹ năng Trung Dũng. Khi Sinh lực của bạn chỉ còn 1, các kỹ năng khác của bạn bị vô hiệu.",
  "Gian Hùng": "Sau khi nhận sát thương, bạn có thể thu lấy lá bài đã gây ra sát thương đó.",
  "Đoạt Sao": "Trong giai đoạn Hành động, bạn có thể bỏ 1 lá bài trên tay để lấy ngẫu nhiên 1 lá bài trên tay của 1 người chơi.",
  "Xả Thân": "Khi bạn trở thành mục tiêu của [Chém], bạn có thể bỏ 1 lá bài để chuyển lá [Chém] đó sang một tướng khác trong phạm vi công kích của bạn."
};
export const SkillIdToName = {
  "thuy-to": "Thủy Tổ",
  "boc-tram-trung": "Bọc Trăm Trứng",
  "thiet-ma": "Thiết Mã",
  "tre-nga": "Tre Ngà",
  "doi-nui": "Dời Núi",
  "hoa-tien": "Hóa Tiên",
  "duyen-tien": "Duyên Tiên",
  "no-than": "Nỏ Thần",
  "banh-chung": "Bánh Chưng",
  "dam-bac": "Đạm Bạc",
  "khai-thien": "Khai Thiên",
  "than-giap": "Thần Giáp",
  "than-hoa": "Thần Hỏa",
  "linh-giam": "Linh Giám",
  "da-trach": "Dạ Trạch",
  "khoi-nghia": "Khởi Nghĩa",
  "tu-chu": "Tự Chủ",
  "khoan-dan": "Khoan Dân",
  "duong-quan": "Dưỡng Quân",
  "nam-quoc-son-ha": "Nam Quốc Sơn Hà",
  "tien-phat": "Tiên Phát",
  "doat-sao": "Đoạt Sáo",
  "chuong-duong": "Chương Dương",
  "tien-phong": "Tiên Phong",
  "bach-dang": "Bạch Đằng",
  "hau-vien": "Hậu Viện",
  "ky-tap": "Kỳ Tập",
  "lan-sau": "Lặn Sâu",
  "binh-ngo": "Bình Ngô",
  "tam-cong": "Tâm Công",
  "nghe-an-ke": "Nghệ An Kế",
  "nhiep-chinh": "Nhiếp Chính",
  "thinh-chinh": "Thính Chính",
  "phat-tam": "Phật Tâm",
  "thong-ngon": "Thông Ngôn",
  "hoa-nghi": "Hòa Nghị",
  "van-don": "Vân Đồn",
  "doi-su": "Đối Sứ",
  "that-tram-so": "Thất Trảm Sớ",
  "duyen-tho": "Duyên Thơ",
  "ho-chu": "Hộ Chủ",
  "hien-hau": "Hiền Hậu",
  "quoc-sac": "Quốc Sắc",
  "hoa-than": "Hòa Thân",
  "nam-duoc": "Nam Dược",
  "uy-chan": "Uy Chấn",
  "binh-loan": "Bình Loạn",
  "khai-quoc": "Khai Quốc",
  "phat-toi": "Phạt Tội",
  "quan-co": "Quân Cơ",
  "dinh-quoc": "Định Quốc",
  "ung-bien": "Ứng Biến",
  "can-gian": "Can Gián",
  "tien-duyen-active": "Tiên Duyên",
  "tien-duyen-passive": "Tiên Duyên (Tỏa Định Kỹ)",
  "pha-quan": "Phá Quân",
  "pha-thanh": "Phá Thành",
  "trung-dung": "Trung Dũng",
  "ho-gia": "Hộ Giá",
  "gian-hung": "Gian Hùng",
  "an-bang": "An Bang",
  "xa-than": "Xả Thân",
  "dieu-duoc": "Diệu Dược",
  "xuan-huong": "Xuân Hương"
};
